### ISSUE TITLE
Custom backgrounds?

### ISSUE THREAD

**Issue by xRamZ** [Oliyy/Material-Design-Discord#1]
I was just wondering if it is currently possible or will be possible to have my own background?
Is there anything I specifically need to do to be able to make it so I can have a custom background or do I have to wait for you to make that possible assuming it's something you're interested in working on. This theme is the only one I know for BeautifulDiscord that has the large profile pictures but I'm realling missing being able to use my own backgrounds.

**Comment by oliyy** [comment]
Uhm sure I can work on that right now! I'll leave an option at the top, I'll also update the readme on how to change it as well

**Comment by xRamZ** [comment]
Thanks

**Comment by oliyy** [comment]
http://i.imgur.com/AfHBcFe.png - This probably isn't what you want, I know and I'm still working on it, but that actually looks pretty cool, just thought I'd put that here.

**Comment by xRamZ** [comment]
I think it would be an interesting idea, if it is possible, to be able to customize seperately. What I mean by that, is be able to have a seperate image for the chat itself (including the user list and channels) and be able to use a seperate image for the area you have added an image to already. I hope you understand what I mean. Up to you.

**Comment by oliyy** [comment]
Yea I know what you mean, it might be difficult to do that, but I will certainly try it.

**Comment by oliyy** [comment]
https://github.com/Oliyy/Material-Design-Discord/tree/soyouwantabackground I added background support, if you have any issues with it please make a new issue and I will do my best to address the issue, it's just changing a URL in the theme.css but different backgrounds for borders etc is not supported yet
